name: 'Build'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    paths:
      - 'release_version/*'

jobs:
  build:
    runs-on: "ubuntu-20.04"
     
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          last_release=$(cat release_version/adguard-home.txt)
          docker buildx build --push\            
            --tag fixtse/adguard-home-wolfi:$last_release \
            --tag fixtse/adguard-home-wolfi:latest \
            --platform linux/amd64,linux/arm64/v8 .
