name: 'Build'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    paths:
      - 'release_version/*'

jobs:
  build:
    runs-on: "ubuntu-latest"
     
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read last release version
        id: get_version
        run: echo "last_release=$(cat release_version/adguard-home.txt)" >> $GITHUB_ENV
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            fixtse/adguard-home-wolfi:${{ env.last_release }}
            fixtse/adguard-home-wolfi:latest
          platforms: linux/amd64,linux/arm64/v8
