name: Check for New Releases

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | \
          jq -r ".tag_name" > release_version/adguard-home.txt
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "$(git status --porcelain)" ] && echo "false" || echo "true")" >> $GITHUB_ENV
      - name: Commit latest release version
        if: env.modified == 'true'
        run: |
          last_release=$(cat release_version/adguard-home.txt)
          git config --global user.name 'Fixt'
          git config --global user.email 'fixtse@gmail.com'
          git commit -am "Release $last_release"
          git push


